### ISSUE TITLE
Broken layout on rotation

### ISSUE THREAD

**Issue by Gargo** [AladinWay/TransitionButton#2]

**Comment by AladinWay** [comment]
First thank you for using the library. Can you please provide more details about the issue and maybe a screenshot and how you are using the button.

**Comment by Gargo** [comment]
what should I provide? run an example in iphone 5 simulator and rotate to landscape - it is evident

**Comment by AladinWay** [comment]
Thank you @Gargo  for reporting what it seems to be an issue, but I guess that there is a misunderstanding because `TransitionButton` is just about the button, and it's not a library for login or forms. So for demo purposes I have added an image of login interface as a background, to put the button in an example context. So that's why the "layout" (which is just an image) seems to be broken when rotating the device. Anyway to avoid the misunderstanding I have update the example project to support only portrait **BUT** the `TransitionButton` library works fine in both landscape and portrait orientation (it's just the background image of the example project does not adapt perfectly to landscape, which is ok, because the hole point is to showcase the button not a login interface)
